# Generated by Django 4.2.7 on 2025-10-26 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du cours', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('instructor', models.CharField(help_text="Nom de l'instructeur", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('economie', 'Économie'), ('litterature', 'Littérature'), ('histoire', 'Histoire')], help_text='Catégorie du cours', max_length=50)),
                ('schedule', models.TextField(help_text='Horaire du cours (ex: Lundi 9h-11h, Mercredi 14h-16h)')),
                ('description', models.TextField(blank=True, help_text='Description du cours', null=True)),
                ('max_students', models.PositiveIntegerField(default=30, help_text="Nombre maximum d'étudiants")),
                ('is_active', models.BooleanField(default=True, help_text='Cours actif ou non')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(help_text="ID de l'étudiant (référence vers student-service)")),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentcourses_set', to='courses.course')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'student_id')},
            },
        ),
    ]
