# Generated by Django 4.2.7 on 2025-10-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_studentcourse_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
